/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CongeladosRouteImport } from './routes/congelados'
import { Route as IndexRouteImport } from './routes/index'

const CongeladosRoute = CongeladosRouteImport.update({
  id: '/congelados',
  path: '/congelados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/congelados': typeof CongeladosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/congelados': typeof CongeladosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/congelados': typeof CongeladosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/congelados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/congelados'
  id: '__root__' | '/' | '/congelados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongeladosRoute: typeof CongeladosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/congelados': {
      id: '/congelados'
      path: '/congelados'
      fullPath: '/congelados'
      preLoaderRoute: typeof CongeladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongeladosRoute: CongeladosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
